bot:
  name: vacancy_finder2_bot
  token: 7010372817:AAHIrDT1UEroijHc0GoZX18FKLp8AsK2Pe4

spring:
  datasource:
    url: jdbc:postgresql://dpg-crs0jd5ds78s73duubj0-a:5432/postgres_bnft
    username: postgres_bnft_user
    password: hZ5IoVlW2zDSQAHlfzlbtVW5HsGEqjjc
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

