bot:
  name: vacancy_finder2_bot
  token: 7010372817:AAHIrDT1UEroijHc0GoZX18FKLp8AsK2Pe4

spring:
  datasource:
    url: jdbc:postgresql://db-postgresql-fra1-89416-do-user-17454160-0.f.db.ondigitalocean.com:25060/defaultdb
    username: doadmin
    password: AVNS_qQ-icD5SFlKwQw6Q9B6
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update